# Generated by Django 6.0.2 on 2026-02-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('POTION', 'Potion'), ('REAGENT', 'Crafting Material')], default='WEAPON', max_length=10)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common (Grey)'), ('RARE', 'Rare (Blue)'), ('EPIC', 'Epic (Purple)'), ('LEGENDARY', 'Legendary (Gold)')], default='COMMON', max_length=10)),
                ('price', models.PositiveIntegerField(help_text='Price in Gold Pieces')),
                ('stock', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True, help_text='Link to an icon or sprite', null=True)),
            ],
        ),
    ]
