# Generated by Django 6.0.2 on 2026-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('POTION', 'Potion'), ('REAGENT', 'Crafting Material'), ('FOOD', 'Food & Drink')], default='WEAPON', max_length=10),
        ),
    ]
